/** Crops offered in the search. Users can also add any name that isn't listed. */
export const CROP_CATALOG: { name: string; group: string }[] = [
  { name: 'Tomato', group: 'Fruiting vegetables' },
  { name: 'Cherry tomato', group: 'Fruiting vegetables' },
  { name: 'Cucumber', group: 'Fruiting vegetables' },
  { name: 'Sweet pepper', group: 'Fruiting vegetables' },
  { name: 'Hot pepper', group: 'Fruiting vegetables' },
  { name: 'Eggplant', group: 'Fruiting vegetables' },
  { name: 'Zucchini', group: 'Fruiting vegetables' },
  { name: 'Melon', group: 'Fruiting vegetables' },
  { name: 'Watermelon', group: 'Fruiting vegetables' },
  { name: 'Strawberry', group: 'Berries' },
  { name: 'Raspberry', group: 'Berries' },
  { name: 'Lettuce', group: 'Leafy greens' },
  { name: 'Spinach', group: 'Leafy greens' },
  { name: 'Cabbage', group: 'Leafy greens' },
  { name: 'Parsley', group: 'Herbs' },
  { name: 'Dill', group: 'Herbs' },
  { name: 'Coriander', group: 'Herbs' },
  { name: 'Basil', group: 'Herbs' },
  { name: 'Green onion', group: 'Herbs' },
  { name: 'Radish', group: 'Root vegetables' },
  { name: 'Carrot', group: 'Root vegetables' },
  { name: 'Lemon', group: 'Fruit trees' },
  { name: 'Flowers (cut)', group: 'Flowers' },
]
